"""phase4b_persistence

Revision ID: 6ba535dbd858
Revises: 
Create Date: 2026-07-12 20:54:49.838854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ba535dbd858'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('raw_text_hash', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('parsed_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_email_unique', 'candidates', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('ix_candidate_hash_unique', 'candidates', ['raw_text_hash'], unique=True, postgresql_where=sa.text('raw_text_hash IS NOT NULL'))
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tfidf_score', sa.Float(), nullable=False),
    sa.Column('bm25_score', sa.Float(), nullable=False),
    sa.Column('skill_overlap_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('weights_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bm25_score >= 0.0 AND bm25_score <= 1.0', name='chk_bm25_score_bounds'),
    sa.CheckConstraint('final_score >= 0.0 AND final_score <= 100.0', name='chk_final_score_bounds'),
    sa.CheckConstraint('skill_overlap_score >= 0.0 AND skill_overlap_score <= 1.0', name='chk_skill_overlap_score_bounds'),
    sa.CheckConstraint('tfidf_score >= 0.0 AND tfidf_score <= 1.0', name='chk_tfidf_score_bounds'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_candidate_id'), 'match_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_results_job_id'), 'match_results', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_results_job_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_candidate_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_table('jobs')
    op.drop_index('ix_candidate_hash_unique', table_name='candidates', postgresql_where=sa.text('raw_text_hash IS NOT NULL'))
    op.drop_index('ix_candidate_email_unique', table_name='candidates', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('candidates')
    # ### end Alembic commands ###
