"""phase6b_pii_encryption

Revision ID: 7dce4675bffb
Revises: 34a54fa2dea2
Create Date: 2026-07-13 10:41:30.002955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dce4675bffb'
down_revision: Union[str, None] = '34a54fa2dea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('email_encrypted', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('email_hash', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('phone_encrypted', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('full_name_encrypted', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('raw_text_encrypted', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('parsed_experience_encrypted', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('parsed_projects_encrypted', sa.Text(), nullable=True))
    op.drop_index('ix_candidate_email_unique', table_name='candidates', postgresql_where='(email IS NOT NULL)')
    op.create_index('ix_candidate_email_unique', 'candidates', ['email_hash'], unique=True, postgresql_where=sa.text('email_hash IS NOT NULL'))
    op.drop_column('candidates', 'email')
    op.drop_column('candidates', 'phone')
    op.drop_column('candidates', 'parsed_projects')
    op.drop_column('candidates', 'raw_text')
    op.drop_column('candidates', 'parsed_experience')
    op.drop_column('candidates', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('parsed_experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('parsed_projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.drop_index('ix_candidate_email_unique', table_name='candidates', postgresql_where=sa.text('email_hash IS NOT NULL'))
    op.create_index('ix_candidate_email_unique', 'candidates', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.drop_column('candidates', 'parsed_projects_encrypted')
    op.drop_column('candidates', 'parsed_experience_encrypted')
    op.drop_column('candidates', 'raw_text_encrypted')
    op.drop_column('candidates', 'full_name_encrypted')
    op.drop_column('candidates', 'phone_encrypted')
    op.drop_column('candidates', 'email_hash')
    op.drop_column('candidates', 'email_encrypted')
    # ### end Alembic commands ###
