"""Add Recruiter and link to Job and Candidate

Revision ID: a05ac3b4525a
Revises: 7dce4675bffb
Create Date: 2026-07-16 20:23:13.671271
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05ac3b4525a'
down_revision: Union[str, None] = '7dce4675bffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name', name='uq_skill_canonical_name')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=False)
    
    # 1. Add columns as nullable
    op.add_column('candidates', sa.Column('recruiter_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_candidates_recruiter_id', 'candidates', 'recruiters', ['recruiter_id'], ['id'], ondelete='CASCADE')
    op.add_column('jobs', sa.Column('recruiter_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_jobs_recruiter_id', 'jobs', 'recruiters', ['recruiter_id'], ['id'], ondelete='CASCADE')

    # 2. Insert default recruiter
    import uuid
    from datetime import datetime, timezone
    system_recruiter_id = uuid.UUID('00000000-0000-0000-0000-000000000000')
    # Dummy argon2 hash for password 'system'
    dummy_hash = "!"
    now = datetime.now(timezone.utc)
    op.execute(
        f"INSERT INTO recruiters (id, email, hashed_password, is_active, created_at, updated_at) "
        f"VALUES ('{system_recruiter_id}', 'system@resumeranker.local', '{dummy_hash}', false, '{now}', '{now}')"
    )

    # 3. Update existing records
    op.execute(f"UPDATE candidates SET recruiter_id = '{system_recruiter_id}' WHERE recruiter_id IS NULL")
    op.execute(f"UPDATE jobs SET recruiter_id = '{system_recruiter_id}' WHERE recruiter_id IS NULL")

    # 4. Alter columns to NOT NULL
    op.alter_column('candidates', 'recruiter_id', nullable=False)
    op.alter_column('jobs', 'recruiter_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'recruiter_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'recruiter_id')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
