"""make_candidate_indexes_recruiter_scoped

Revision ID: c026cb8518e1
Revises: a05ac3b4525a
Create Date: 2026-07-17 07:02:19.705657
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c026cb8518e1'
down_revision: Union[str, None] = 'a05ac3b4525a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_email_unique', table_name='candidates', postgresql_where='(email_hash IS NOT NULL)')
    op.create_index('ix_candidate_email_unique', 'candidates', ['recruiter_id', 'email_hash'], unique=True, postgresql_where=sa.text('email_hash IS NOT NULL'))
    op.drop_index('ix_candidate_hash_unique', table_name='candidates', postgresql_where='(raw_text_hash IS NOT NULL)')
    op.create_index('ix_candidate_hash_unique', 'candidates', ['recruiter_id', 'raw_text_hash'], unique=True, postgresql_where=sa.text('raw_text_hash IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_hash_unique', table_name='candidates', postgresql_where=sa.text('raw_text_hash IS NOT NULL'))
    op.create_index('ix_candidate_hash_unique', 'candidates', ['raw_text_hash'], unique=True, postgresql_where='(raw_text_hash IS NOT NULL)')
    op.drop_index('ix_candidate_email_unique', table_name='candidates', postgresql_where=sa.text('email_hash IS NOT NULL'))
    op.create_index('ix_candidate_email_unique', 'candidates', ['email_hash'], unique=True, postgresql_where='(email_hash IS NOT NULL)')
    # ### end Alembic commands ###
