"""add_embedding_columns_for_phase12

Revision ID: fdf91f42720c
Revises: c026cb8518e1
Create Date: 2026-07-17 09:10:15.576409
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'fdf91f42720c'
down_revision: Union[str, None] = 'c026cb8518e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('jobs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('match_results', sa.Column('vector_score', sa.Float(), nullable=False))
    op.create_check_constraint('chk_vector_score_bounds', 'match_results', 'vector_score >= 0.0 AND vector_score <= 1.0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_vector_score_bounds', 'match_results', type_='check')
    op.drop_column('match_results', 'vector_score')
    op.drop_column('jobs', 'embedding')
    op.drop_column('candidates', 'embedding')
    # Note: We don't drop the vector extension as other migrations may depend on it
    # ### end Alembic commands ###
